# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interfacecontroller.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19interfacecontroller.proto\x12\x0frobotcontroller\"\x1d\n\ractionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0b\x61\x63tionReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\\\n\x0cwebinterface\x12L\n\nSendAction\x12\x1e.robotcontroller.actionRequest\x1a\x1c.robotcontroller.actionReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interfacecontroller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTIONREQUEST']._serialized_start=46
  _globals['_ACTIONREQUEST']._serialized_end=75
  _globals['_ACTIONREPLY']._serialized_start=77
  _globals['_ACTIONREPLY']._serialized_end=107
  _globals['_WEBINTERFACE']._serialized_start=109
  _globals['_WEBINTERFACE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
